In [3]:
!pip install numpy

import numpy as np

In [4]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [5]:
a[0]

1

In [6]:
a[3] = 8
a

array([1, 2, 3, 8, 5])

In [7]:
a[0:4]

array([1, 2, 3, 8])

#### Higher dimensional array

In [20]:
b = np.array([[1,2,3],[3,4,5],[5,6,7]])
b[:3]

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

#### Array Attributes

In [14]:
b.ndim

2

In [11]:
a.shape

(5,)

In [12]:
a.size

5

In [13]:
b.size

9

In [14]:
a.dtype

dtype('int32')

In [15]:
# Syntax: a = np._____(shape=(),dtype=())
c = np.zeros((3,4),dtype = int)
c

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
d = np.ones((3,4))
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
# ts creates garbage value just for take place in array
e = np.empty((2,2),dtype = int)
e

array([[ 1520645912,  1950122683],
       [-1648127402,   408837765]])

In [49]:
#
f = np.arange(5,10,1)
f

array([5, 6, 7, 8, 9])

In [18]:
f1 = np.arange(5,10,1.5)
f1

array([5. , 6.5, 8. , 9.5])

In [51]:
np.linspace(5,10,num = 20,dtype = None,axis = 0) # It count end value also


array([ 5.        ,  5.26315789,  5.52631579,  5.78947368,  6.05263158,
        6.31578947,  6.57894737,  6.84210526,  7.10526316,  7.36842105,
        7.63157895,  7.89473684,  8.15789474,  8.42105263,  8.68421053,
        8.94736842,  9.21052632,  9.47368421,  9.73684211, 10.        ])

In [23]:
np.linspace(1,100,50,dtype=int)

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97, 100])

In [24]:
# Using concatenate
a = np.array([3,4,2,7,8,9,10])
a = np.sort(a)

In [26]:
b = np.array([20,40,30,60])

c = np.concatenate((a,b))
c

array([ 2,  3,  4,  7,  8,  9, 10, 20, 40, 30, 60])

In [40]:
#Axis 0 use for row & axis 1 use for column; thats why it counted columns in both list and it return in row 
x = np.array([[1,2],[7,8]])
y = np.array([[3,4],[5,6]])

z = np.concatenate((x,y),axis = 1)
z

array([[1, 2, 3, 4],
       [7, 8, 5, 6]])

#### Reshape Array

In [46]:
a1 = z.reshape(4,2) # 4 is define for column number and 2 is for rows
a1

array([[1, 2],
       [3, 4],
       [7, 8],
       [5, 6]])

#### Basic array operations

In [59]:
# Syntax: data + ones 
data = np.array([1,2])
ones_arr = np.array(2, dtype = int)
x = data + ones_arr
x

array([3, 4])

In [60]:
data = np.array([1,2])
ones_arr = np.array(2,dtype = int)
x = data - ones_arr
x

array([-1,  0])

In [61]:
data = np.array([1,2])
ones_arr = np.array(2,dtype = int)
x = data * ones_arr
x

array([2, 4])

In [62]:
data = np.array([1,2])
ones_arr = np.array(2,dtype = int)
x = data / ones_arr
x

array([0.5, 1. ])

In [63]:
b = 2*data
b

array([2, 4])

#### Imp

In [64]:
# Central tendancy :
'''
1. Mean/average = it is the ration of sum of the all observation and total num of observations
    formula:
            Mean = (Sum of all the observations/Total number of observations)
            
2. Mode = highest number of frequency(here freq. means count)
    it is the value that is repeatedly occuring in a given set of observation
    
3. Median = n/2 (if n is odd(for eg:9,11) then take average of middle two numbers)
    median is the middle observation in a sorted list of obseravtion
    formula:
            med = (n+1/2)th observation

'''
# Majors of dispersion:
'''
1. Variance = It is the stattistical majorment of how far each num in the 
            set of observations is from the mean
            Formula :
                sigma**2
2. Statndard Deviation = It is calculated as the square root of variance
            Formula :
                sigma
'''

'\n1. Variance = It is the stattistical majorment of how far each num in the \n            set of observations is from the mean\n            Formula :\n                sigma**2\n2. Statndard Deviation = It is calculated as the square root of variance\n            Formula :\n                sigma\n'

In [65]:
data.min()

1

In [66]:
data.max()

2

In [76]:
data = np.array([[1,2,3],[0,4,5],[6,7,8]])
data.max()
data.min()
data.max(axis=1)
data.min(axis=1)
data.max(axis=0)
data.min(axis=0)

array([0, 2, 3])

In [77]:
data.sum(axis=0)

array([ 7, 13, 16])

In [78]:
data.sum(axis=1)

array([ 6,  9, 21])

In [82]:
data.sum(axis=1)
data.mean(axis=0)

array([2.33333333, 4.33333333, 5.33333333])

#### Generating random

In [28]:
random_int = np.random.randint(10)
random_int

random_int = np.random.randint(5,10)
random_int

5

In [36]:
random_array = np.random.randint(5,10, size=(3,3))
random_array

random_array = np.random.randint(10, size=(3,3)) # If we dont take initial value
random_array

random_array = np.random.randint(-5,10, size=(3,3)) # If we take negative initial value
random_array

array([[ 7,  7, -4],
       [ 9, -1,  2],
       [ 2,  5,  1]])

In [40]:
random_array.T

array([[ 7,  9,  2],
       [ 7, -1,  5],
       [-4,  2,  1]])

In [41]:
random_array.transpose()

array([[ 7,  9,  2],
       [ 7, -1,  5],
       [-4,  2,  1]])

In [42]:
np.flip(random_array)

array([[ 1,  5,  2],
       [ 2, -1,  9],
       [-4,  7,  7]])

In [43]:
np.flip(random_array,axis=0)

array([[ 2,  5,  1],
       [ 9, -1,  2],
       [ 7,  7, -4]])

In [44]:
# Flatten makes copy of main array
# Ravel makes changes in main array

flattened_array = random_array.flatten()
flattened_array

array([ 7,  7, -4,  9, -1,  2,  2,  5,  1])

In [46]:
flattened_array[3] = 5
print(flattened_array)
print(random_array)

[ 7  7 -4  5 -1  2  2  5  1]
[[ 7  7 -4]
 [ 9 -1  2]
 [ 2  5  1]]


In [47]:
ravelled_array = random_array.ravel()
ravelled_array[3] = 5
print(ravelled_array)
print(random_array)

[ 7  7 -4  5 -1  2  2  5  1]
[[ 7  7 -4]
 [ 5 -1  2]
 [ 2  5  1]]


In [50]:
arr = np.array([[1,2,3],[4,5,6]]) # array[0] = [1,2,3] & array[1] = [4,5,6] then return again 
arr[1,2]

6